---
title: "Project1"
author: "Jose Singer-Freeman"
date: "2023-06-15"
output: github_document
---

## Introduction

This vignette show stock prices for publicly-traded life insurance companies for the past x days.  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The packages needed to run the code to create this vignette are the following:  


- jsonlite
- httr  
- tidyverse

In addition, I used the following packages to process the data and perform other tasks.



```{r}

library(httr)
library(plyr)
library(jsonlite)
library(tidyverse)
library(ggplot2)



#Price/transaction info for only One ticker for several days 


get_daily_info<-function(tick, daterange){
base<-'https://api.polygon.io/v2/aggs/ticker/'
ticker<-tick
range<-'/range/1/day/'
dates<-daterange
adjusted<-'?adjusted=true&sort=asc&limit=120'
info_key<-'&apiKey=7FTp6uzAjKcWUI1BJEO7WppG3wyOZOy9'
API_URL<-paste0(base,ticker, range, dates, adjusted, info_key)
aggr_ticker_info<-GET(API_URL)
df_ticker_aggr<-fromJSON(rawToChar(aggr_ticker_info$content))

df_aggr_ticker_results<-as_tibble(df_ticker_aggr$results)%>%
  dplyr::mutate(date=as.POSIXct(t/1000, origin="1970-01-01"), ticker=df_ticker_aggr$ticker)%>%
  dplyr::rename(volume=v, weighted_price=vw, open_price=o, close_price=c, high_price=h, low_price=l, num_transactions=n)%>%
  dplyr::select(-t)%>%
  dplyr::relocate(ticker)
print(df_aggr_ticker_results)
return(list(df_aggr_ticker_results))
}

#Function to cycle through top 5 stocks and obtain the daily info

daterange<-'2023-01-01/2023-05-01'
df_daily<-data.frame(T=character(), 
                     v=integer(),
                     vw=double(),
                     o=double(),
                     c=double(),
                     h=double(),
                     l=double(),
                     n=double(),
                     t=double())


for (i in 1:5){
  oo<-data.frame(get_daily_info(top_5_tickers[i], daterange))
  df_daily<-rbind.fill(df_daily, oo)
}

ggplot(df_daily, aes(y=weighted_price, x=ticker))+geom_boxplot()


df_daily_summary<-df_daily%>%dplyr::group_by(ticker)%>%dplyr::summarise(mean_price=mean(weighted_price),sd_price=sd(weighted_price))

sd(daily_info$weighted_price)
mean(daily_info$weighted_price)

# All equity securities (stock, ETFs) prices/transactions for one day (exluding QQ)

date<-'2023-03-20'
base<-'https://api.polygon.io/v2/aggs/grouped/locale/us/market/stocks/'
adjusted<-'?adjusted=true'
info_key<-'&apiKey=7FTp6uzAjKcWUI1BJEO7WppG3wyOZOy9'
API_URL<-paste0(base,date, adjusted, info_key)
daily_stock_info<-GET(API_URL)
df_daily_stock<-fromJSON(rawToChar(daily_stock_info$content))


#Format date/time of selected date (which is originally the number of seconds from 1/1/1970). 


df_daily_stock_results<-df_daily_stock$results%>%
  mutate(date=as.POSIXct(t/1000, origin="1970-01-01"))%>%dplyr::rename(ticker=T, volume=v, weighted_price=vw, open_price=o, close_price=c, high_price=h, low_price=l, num_transactions=n)%>%
  select(-t)

df_daily_stock_results


#Pick the top 5 tickers most heavily traded by volume
#Also create a variable for the change in price for the day.

top_5<-df_daily_stock_results%>%
  mutate(price_change=close_price/open_price-1, Gain=if_else(price_change>0,1,0))%>%
  arrange(desc(price_change))%>%
  slice(seq(5))
  

f<-paste0("Change in Price for top-5 stocks traded on ",date)  # This is the title for the graph that follows

ggplot(data=top_5, aes(x=ticker, y=price_change, fill=Gain))+geom_bar(stat="identity",show.legend = FALSE)+labs(title=f, y="Price Increase")



#PROVIDE TICKER AND OBTAIN DETAILS OF THE  COMPANY


#Function to obtain company information

#create vector with top 5 ticker names
top_5_tickers<-top_5$ticker

# Function to get name of company, number of employees, outstanding shares for the top 5 tickers:

get_company_info<-function(xyz){
  #generate URL for the API for 1 ticker
  ticker<-xyz
  base<-'https://api.polygon.io/v3/reference/tickers/'
  info_key<-'?apiKey=7FTp6uzAjKcWUI1BJEO7WppG3wyOZOy9'
  API_URL<-paste0(base,ticker,info_key)
  #connect to API
  ticker_info<-GET(API_URL)
  #Convert retrieved information (JSON format) to an R list 
  df_ticker<-fromJSON(rawToChar(ticker_info$content))

  #Form a vector from the various dispersed variables for the 1 ticker 
df_tick_result<-cbind(
  ticker=df_ticker$results$ticker_root,
  company=df_ticker$results$name,
  outstanding=df_ticker$results$share_class_shares_outstanding,
  employees=df_ticker$results$total_employees)
return(df_tick_result)
}


#Initialize dataframe that will store information for 10 companies 
df_ticker_res<-data.frame(
  ticker=character(),
  company=character(), 
  outstanding=integer(), 
  employees=integer())


#loop through the 5 tickers to invoke the function that obtains the company information for each

for (i in 1:5){
  oo<-data.frame(get_company_info(top_5_tickers[i]))
  df_ticker_res<-plyr::rbind.fill(df_ticker_res, oo)
}

df_ticker_res








cat(paste("Company name/Security: ",
           df_ticker$results$name,'\n',
           "Address: ",df_ticker$results$address$address1,
          ",",df_ticker$results$address$city,
          df_ticker$results$address$state, '\n',
          "Number of employees:",
          format(df_ticker$results$total_employees,big.mark=","),'\n',
          "Outstanding shares:",
          format(df_ticker$results$share_class_shares_outstanding,scientific=FALSE,big.mark=","),'\n' 
          , sep=" ")
    )


ggplot(data=df_ticker_res, aes(outstanding, 

#One foreign exchange rate for multiple dates

base<-'https://api.polygon.io/v2/aggs/ticker/'
currency<-'C:EURUSD/range/1/day/'
dates<-'2023-01-09/2023-05-09'
adjusted<-'?adjusted=true&sort=asc&limit=5000'
info_key<-'&apiKey=7FTp6uzAjKcWUI1BJEO7WppG3wyOZOy9'
API_URL<-paste0(base,currency, dates, adjusted, info_key)
fx_aggr_info<-GET(API_URL)
df_fx_aggr<-fromJSON(rawToChar(fx_aggr_info$content))


#Function to remove "C:" from ticker
remove_C<-function(x){gsub("C:","",x)}


df_fx_aggr_results<-df_fx_aggr$results%>%
  mutate(date=as.POSIXct(t/1000, origin="1970-01-01"), ticker=remove_C(df_fx_aggr$ticker))%>%
  rename(volume=v, weighted_volum=vw, open_price=o, close_price=c, high_price=h, low_price=l, num_transactions=n)%>%
  select(-t)%>%
  relocate(ticker)


#All foreign exchange rates for one  day

date<-'2023-02-09?'
base<-'https://api.polygon.io/v2/aggs/grouped/locale/global/market/fx/'
adjusted<-'adjusted=true'
info_key<-'&apiKey=7FTp6uzAjKcWUI1BJEO7WppG3wyOZOy9'
API_URL<-paste0(base,date,adjusted, info_key)
fx_info<-GET(API_URL)
df_fx_daily<-fromJSON(rawToChar(fx_info$content))


df_fx_daily_results<-df_fx_daily$results%>%
  mutate(date=as.POSIXct(t/1000, origin="1970-01-01"), T=remove_C(T))%>%
  rename(ticker=T, volume=v, weighted_volum=vw, open_price=o, close_price=c, high_price=h, low_price=l, num_transactions=n)%>%
  select(-t)


```


